# Generated by Django 5.2 on 2025-07-19 11:18

import django.core.validators
import phrase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersearchquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_dialogu_bbc8a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_dialogu_91ad8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_video_u_3900ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_dialogu_19a519_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_transla_cf6e73_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_transla_666ef2_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_play_co_32fe8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_search__be7c2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_movie_i_558a9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_movie_i_93de6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='dialoguetable',
            name='dialogue_ta_is_acti_142560_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_movie_t_6b9c6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_release_7db6cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_directo_da9783_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_genre_a4b892_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_imdb_ra_b65fc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_data_qu_b1cd12_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_view_co_b2faac_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_movie_t_57370c_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_is_acti_9c4b19_idx',
        ),
        migrations.RemoveIndex(
            model_name='movietable',
            name='movie_table_created_dbad42_idx',
        ),
        migrations.RemoveIndex(
            model_name='requesttable',
            name='request_tab_request_8fbc58_idx',
        ),
        migrations.RemoveIndex(
            model_name='requesttable',
            name='request_tab_request_394199_idx',
        ),
        migrations.RemoveIndex(
            model_name='requesttable',
            name='request_tab_search__bd5e25_idx',
        ),
        migrations.RemoveIndex(
            model_name='requesttable',
            name='request_tab_last_se_d2dde4_idx',
        ),
        migrations.RemoveIndex(
            model_name='requesttable',
            name='request_tab_transla_5497aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='requesttable',
            name='request_tab_is_acti_00e82b_idx',
        ),
        migrations.RemoveIndex(
            model_name='requesttable',
            name='request_tab_created_5a6457_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersearchquery',
            name='phrase_user_origina_6f8d93_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersearchquery',
            name='phrase_user_session_a8570c_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersearchquery',
            name='phrase_user_search__a60071_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersearchquery',
            name='phrase_user_has_res_096b6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersearchresult',
            name='phrase_user_relevan_766017_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersearchresult',
            name='phrase_user_click_p_af0d6b_idx',
        ),
        migrations.AlterField(
            model_name='dialoguetable',
            name='video_url',
            field=phrase.models.SecureURLField(max_length=600, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='비디오 URL'),
        ),
        migrations.AlterField(
            model_name='movietable',
            name='imdb_url',
            field=phrase.models.SecureURLField(blank=True, max_length=600, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='IMDB URL'),
        ),
        migrations.AlterField(
            model_name='movietable',
            name='poster_url',
            field=phrase.models.SecureURLField(blank=True, max_length=600, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='포스터 URL'),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='request_phrase',
            field=models.CharField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(500)], verbose_name='요청구문'),
        ),
    ]
