# Generated by Django 5.2 on 2025-07-19 11:48

import django.core.validators
import phrase.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phrase', '0002_alter_usersearchquery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialoguetable',
            name='dialogue_phrase_ja',
        ),
        migrations.RemoveField(
            model_name='dialoguetable',
            name='dialogue_phrase_zh',
        ),
        migrations.AlterField(
            model_name='dialoguetable',
            name='video_url',
            field=phrase.models.SecureURLField(max_length=600, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='비디오 URL'),
        ),
        migrations.AlterField(
            model_name='movietable',
            name='imdb_url',
            field=phrase.models.SecureURLField(blank=True, max_length=600, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='IMDB URL'),
        ),
        migrations.AlterField(
            model_name='movietable',
            name='poster_url',
            field=phrase.models.SecureURLField(blank=True, max_length=600, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='포스터 URL'),
        ),
    ]
