# Generated by Django 5.2 on 2025-07-19 11:59

import django.core.validators
import phrase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase', '0003_remove_dialoguetable_dialogue_phrase_ja_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cacheinvalidation',
            options={'verbose_name': '캐시 무효화', 'verbose_name_plural': '캐시 무효화들'},
        ),
        migrations.AlterModelOptions(
            name='usersearchquery',
            options={'verbose_name': '사용자 검색 쿼리', 'verbose_name_plural': '사용자 검색 쿼리들'},
        ),
        migrations.AlterModelOptions(
            name='usersearchresult',
            options={'verbose_name': '사용자 검색 결과', 'verbose_name_plural': '사용자 검색 결과들'},
        ),
        migrations.RenameIndex(
            model_name='cacheinvalidation',
            new_name='cache_inval_model_n_73c9a9_idx',
            old_name='phrase_cach_model_n_cede31_idx',
        ),
        migrations.RenameIndex(
            model_name='cacheinvalidation',
            new_name='cache_inval_created_d3d200_idx',
            old_name='phrase_cach_created_b236ec_idx',
        ),
        migrations.AlterUniqueTogether(
            name='movietable',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dialoguetable',
            name='dialogue_phrase',
            field=phrase.models.MySQLTextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='영어 대사'),
        ),
        migrations.AlterField(
            model_name='dialoguetable',
            name='dialogue_phrase_ko',
            field=phrase.models.MySQLTextField(blank=True, null=True, verbose_name='한글 대사'),
        ),
        migrations.AlterField(
            model_name='dialoguetable',
            name='search_vector',
            field=models.CharField(blank=True, db_index=True, help_text='전문 검색을 위한 정규화된 텍스트', max_length=1000, verbose_name='검색 벡터'),
        ),
        migrations.AlterField(
            model_name='dialoguetable',
            name='video_url',
            field=phrase.models.SecureURLField(max_length=600, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='비디오 URL'),
        ),
        migrations.AlterField(
            model_name='movietable',
            name='imdb_url',
            field=phrase.models.SecureURLField(blank=True, max_length=600, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='IMDB URL'),
        ),
        migrations.AlterField(
            model_name='movietable',
            name='poster_url',
            field=phrase.models.SecureURLField(blank=True, max_length=600, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='포스터 URL'),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='request_phrase',
            field=models.CharField(db_index=True, max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(500)], verbose_name='요청구문'),
        ),
        migrations.AddIndex(
            model_name='dialoguetable',
            index=models.Index(fields=['movie', 'dialogue_start_time'], name='dialogue_movie_time_idx'),
        ),
        migrations.AddIndex(
            model_name='dialoguetable',
            index=models.Index(fields=['translation_quality'], name='dialogue_quality_idx'),
        ),
        migrations.AddIndex(
            model_name='dialoguetable',
            index=models.Index(fields=['translation_method'], name='dialogue_method_idx'),
        ),
        migrations.AddIndex(
            model_name='dialoguetable',
            index=models.Index(fields=['play_count'], name='dialogue_play_count_idx'),
        ),
        migrations.AddIndex(
            model_name='dialoguetable',
            index=models.Index(fields=['search_vector'], name='dialogue_search_idx'),
        ),
        migrations.AddIndex(
            model_name='movietable',
            index=models.Index(fields=['movie_title', 'release_year'], name='movie_title_year_idx'),
        ),
        migrations.AddIndex(
            model_name='movietable',
            index=models.Index(fields=['director'], name='movie_director_idx'),
        ),
        migrations.AddIndex(
            model_name='movietable',
            index=models.Index(fields=['production_country'], name='movie_country_idx'),
        ),
        migrations.AddIndex(
            model_name='movietable',
            index=models.Index(fields=['imdb_rating'], name='movie_rating_idx'),
        ),
        migrations.AlterModelTable(
            name='cacheinvalidation',
            table='cache_invalidation',
        ),
        migrations.AlterModelTable(
            name='usersearchquery',
            table='user_search_query',
        ),
        migrations.AlterModelTable(
            name='usersearchresult',
            table='user_search_result',
        ),
    ]
